### ISSUE TITLE
Use pdb 0.3 to get features for address mapping without needing PE files

### ISSUE THREAD

**Issue by luser** [mstange/profiler-get-symbols#1]
Version 0.3 of the pdb crate was released recently and it includes some new features that should let you not require PE files in this crate. If you call [`PDB::address_map`](https://docs.rs/pdb/0.3.0/pdb/struct.PDB.html#method.address_map) you'll get back an `AddressMap` object, and then when you iterate over `pdb::PublicSymbol` and `pdb::ProcedureSymbol` objects you can pass that to the [`to_rva`](https://docs.rs/pdb/0.3.0/pdb/struct.PdbInternalSectionOffset.html#method.to_rva) method on their `offset` fields which will do the proper address translation for you.

Additionally it looks like that change you're relying on from that GitHub fork of the crate [has been merged](https://github.com/willglynn/pdb/pull/26) so relying on 0.3 direct from crates.io should be fine.

**Comment by mstange** [comment]
Thanks for filing and fixing this! Doing this was already on my list, but I hadn't started working on it yet, so your PR came at the perfect time.
