### ISSUE TITLE
Synthesize placeholder names for missing symbols

### ISSUE THREAD

**Issue by mstange** [mstange/profiler-get-symbols#23]
Some system libraries on macOS don't have a complete symbol table. To prevent assigning incorrect symbols from an incomplete symbol table, it would be great to create synthetic `FUN_f4a4b` function names for symbol-less functions.

We can make use of `LC_FUNCTION_STARTS` to get the start addresses of symbol-less functions.

**Comment by mstange** [comment]
Let's make this issue generic across platforms. The most important case to fix is the Linux libxul.so case: If the Mozilla symbol server doesn't have symbols for libxul.so, we often try to get the symbols from the stripped binary, and end up with completely misleading function names.

On Linux + Android we can get function starts from eh_frame or eh_frame_hdr. On macOS we can get them from LC_FUNCTION_STARTS or from __unwind_info.

**Comment by mstange** [comment]
> On macOS we can get them from LC_FUNCTION_STARTS or from __unwind_info.

It would be better to get them from LC_FUNCTION_STARTS, because __unwind_info often merges consecutive functions with the same unwind info into a single entry, discarding the individual function start addresses.

**Comment by mstange** [comment]
We hit the same issue on Windows when we fall back to getting symbols from the "exports" of the dll / exe. Example profile: https://share.firefox.dev/3IMTwhd

**Comment by gregtatum** [comment]
Here is the [re-symbolicated profile](https://profiler.firefox.com/public/2wgmaw9g0z4mnsw4x5xtp28zce7qjg25wecp8yr/flame-graph/?globalTrackOrder=awe0w9&hiddenGlobalTracks=1w7&hiddenLocalTracksByPid=9808-0w3~4908-0~15460-0~10084-0~9488-01~12444-0~17936-0w9&localTrackOrderByPid=9808-40w3~4908-0~15460-0~10084-0~9488-10~12444-0~17936-a0w9&thread=0&timelineType=cpu-category&v=6). In this case having wrong symbols was worse than no symbols, and took a lot of investigation.

**Comment by mstange** [comment]
0c413f09171494571044c0f42641ee06d6dcba9b fixed this for Linux / Android, 6169011926e908e165971dfb32e967d677072c19 for macOS, and 7c8e394c4eba72e2a2308aba0e6fbe676b0fa256 for Windows.
